---
# Namespace for HealOps
apiVersion: v1
kind: Namespace
metadata:
  name: healops-system
---
# ServiceAccount for the agent
apiVersion: v1
kind: ServiceAccount
metadata:
  name: healops-agent
  namespace: healops-system
---
# ClusterRole - Read logs from all pods
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: healops-agent
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
---
# ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: healops-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: healops-agent
subjects:
  - kind: ServiceAccount
    name: healops-agent
    namespace: healops-system
---
# ConfigMap - HealOps configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: healops-config
  namespace: healops-system
data:
  healops-endpoint: "{{HEALOPS_ENDPOINT}}"
  fluent-bit.conf: |
    [SERVICE]
        Flush        5
        Daemon       Off
        Log_Level    info

    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Parser            docker
        Tag               kube.*
        Refresh_Interval  5
        Mem_Buf_Limit     50MB
        Skip_Long_Lines   On

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On

    [OUTPUT]
        Name   http
        Match  *
        Host   {{HEALOPS_HOST}}
        Port   {{HEALOPS_PORT}}
        URI    /ingest/logs
        Format json
        Header X-API-Key {{HEALOPS_API_KEY}}
        tls    On
        tls.verify Off

  parsers.conf: |
    [PARSER]
        Name   docker
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%LZ
---
# Secret - API Key (user must replace)
apiVersion: v1
kind: Secret
metadata:
  name: healops-secret
  namespace: healops-system
type: Opaque
stringData:
  api-key: "{{HEALOPS_API_KEY}}"
---
# DaemonSet - Fluent Bit agent on every node
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: healops-agent
  namespace: healops-system
  labels:
    app: healops-agent
spec:
  selector:
    matchLabels:
      app: healops-agent
  template:
    metadata:
      labels:
        app: healops-agent
    spec:
      serviceAccountName: healops-agent
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: fluent-bit
          image: fluent/fluent-bit:2.1
          env:
            - name: HEALOPS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: healops-secret
                  key: api-key
            - name: HEALOPS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: healops-config
                  key: healops-endpoint
          volumeMounts:
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: fluent-bit-config
          configMap:
            name: healops-config
