export const mockIncidents = [
  {
    id: 1,
    title: "High Memory Usage in Payment Service",
    status: "RESOLVED",
    severity: "HIGH",
    service_name: "payment-service",
    source: "datadog",
    created_at: "2023-10-27T10:00:00Z",
    last_seen_at: "2023-10-27T10:15:00Z",
    root_cause: "Memory leak in worker process",
    action_taken: "restart_container",
  },
  {
    id: 2,
    title: "Database Connection Timeout",
    status: "INVESTIGATING",
    severity: "CRITICAL",
    service_name: "user-db",
    source: "cloudwatch",
    created_at: "2023-10-27T10:30:00Z",
    last_seen_at: "2023-10-27T10:35:00Z",
    root_cause: "Pending analysis...",
    action_taken: null,
  },
  {
    id: 3,
    title: "Frontend 500 Errors",
    status: "OPEN",
    severity: "MEDIUM",
    service_name: "frontend-proxy",
    source: "sentry",
    created_at: "2023-10-27T11:00:00Z",
    last_seen_at: "2023-10-27T11:05:00Z",
    root_cause: null,
    action_taken: null,
  },
];
